import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    projects: [
      'packages/i18n',
      'packages/protocol',
      'packages/plugin-api',
      'packages/kernel',
      'packages/api',
      'packages/client',
      'plugins/workspace-local',
      'apps/bytebureau',
      'apps/docs',
      'scripts',
    ],
    coverage: {
      provider: 'v8',
      include: [
        'packages/*/src/**/*.ts',
        'plugins/*/src/**/*.ts',
        'scripts/**/*.ts',
        'apps/docs/scripts/**/*.ts',
        'apps/bytebureau/src/locale.ts',
        'apps/bytebureau/src/context.ts',
        'apps/bytebureau/src/output.ts',
        'apps/bytebureau/src/run.ts',
        'apps/bytebureau/src/errors.ts',
        'apps/bytebureau/src/kernel-home.ts',
        'apps/bytebureau/src/resource.ts',
        'apps/bytebureau/src/usage-error.ts',
        'apps/bytebureau/src/render/**/*.ts',
        'apps/bytebureau/src/commands/run-session.ts',
        'apps/bytebureau/src/commands/run-output.ts',
        'apps/bytebureau/src/commands/run-follow.ts',
        'apps/bytebureau/src/commands/refusable.ts',
        'apps/bytebureau/src/commands/sessions-prompt.ts',
        'apps/bytebureau/src/commands/ask-answer.ts',
        'apps/bytebureau/src/drain.ts',
        // The Bureau as the tests run it in-process; a daemon is started on demand, and the kernel of --no-daemon opened, only in CLI subprocesses
        'apps/bytebureau/src/bureau/ensure-daemon.ts',
        'apps/bytebureau/src/bureau/local.ts',
        'apps/bytebureau/src/bureau/open-local.ts',
        'apps/bytebureau/src/bureau/remote.ts',
        'apps/bytebureau/src/bureau/resolve.ts',
        'apps/bytebureau/src/bureau/session-env.ts',
        'apps/bytebureau/src/bureau/with-bureau.ts',
        // The daemon modules the tests run in-process; foreground.ts and spawn.ts run only in the daemon and CLI subprocesses
        'apps/bytebureau/src/daemon/announce.ts',
        'apps/bytebureau/src/daemon/exec-args.ts',
        'apps/bytebureau/src/daemon/files.ts',
        'apps/bytebureau/src/daemon/hosts.ts',
        'apps/bytebureau/src/daemon/lock.ts',
        'apps/bytebureau/src/daemon/lock-holder.ts',
        'apps/bytebureau/src/daemon/lock-mutex.ts',
        'apps/bytebureau/src/daemon/private-file.ts',
        'apps/bytebureau/src/daemon/publish.ts',
        'apps/bytebureau/src/daemon/server-info.ts',
        'apps/bytebureau/src/daemon/start.ts',
        'apps/bytebureau/src/daemon/stop.ts',
        'apps/bytebureau/src/daemon/token.ts',
        'apps/bytebureau/src/daemon/wait.ts',
      ],
      exclude: ['packages/i18n/src/paraglide/**', '**/*.test.ts', '**/testing/**', '**/gen/**'],
      thresholds: { lines: 80, branches: 80 },
      reporter: ['text', 'lcov'],
    },
  },
})
