import { defineConfig } from '@hey-api/openapi-ts'

// The generated client is bundled into the output: packages/client has no runtime dependency on hey-api
// Every consumer compiles the client from source under its own strict options, which the bundled client does not meet
export default defineConfig({
  input: '../../packages/api/openapi.json',
  output: {
    path: '../../packages/client/src/gen',
    header: ['// This file is auto-generated by @hey-api/openapi-ts', '// @ts-nocheck'],
  },
  plugins: ['@hey-api/client-fetch', '@hey-api/sdk', '@hey-api/typescript'],
})
